In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from keras.models import load_model
from tqdm import tqdm_notebook
from sklearn.metrics import mean_squared_error

In [2]:
model = load_model('model1_waterflow_mse_32.hdf5')

In [3]:
df = pd.read_csv('Sub0-RAW.csv')
df.head()

Dates  Year  Month  Day    Hours  Precipitation  Temperature  Outflow
0  10/1/1980  1980     10    1  0:00:00            0.0      102.992      5.0
1  10/1/1980  1980     10    1  1:00:00            0.0       97.790      5.0
2  10/1/1980  1980     10    1  2:00:00            0.0       92.588      5.0
3  10/1/1980  1980     10    1  3:00:00            0.0       87.404      5.0
4  10/1/1980  1980     10    1  4:00:00            0.0       85.172      5.0

In [7]:
len(model.weights),len(model.weights[1])

TypeError: object of type 'ResourceVariable' has no len()

In [11]:
type((model.weights)[1])

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [1]:
import torch

a = torch.arange(8).reshape(2, 2, 2)
b = torch.arange(12).reshape(2, 2, 3)
my_list = [a, b]

In [2]:
my_list

[tensor([[[0, 1],
          [2, 3]],
 
         [[4, 5],
          [6, 7]]]),
 tensor([[[ 0,  1,  2],
          [ 3,  4,  5]],
 
         [[ 6,  7,  8],
          [ 9, 10, 11]]])]

In [3]:
my_tensor = torch.cat([a, b], dim=2)
print(my_tensor.shape) #torch.Size([2, 2, 5])

torch.Size([2, 2, 5])


In [4]:
my_tensor

tensor([[[ 0,  1,  0,  1,  2],
         [ 2,  3,  3,  4,  5]],

        [[ 4,  5,  6,  7,  8],
         [ 6,  7,  9, 10, 11]]])

In [11]:
a = ([[ 0,  1,  0,  1,  2],
         [ 2,  3,  3,  4,  5]],

        [[ 4,  5,  6,  7,  8],
         [ 6,  7,  9, 10, 11]])

In [12]:
type(a)

tuple

In [13]:
b = torch.LongTensor(a)
type(b)

torch.Tensor

In [14]:
b

tensor([[[ 0,  1,  0,  1,  2],
         [ 2,  3,  3,  4,  5]],

        [[ 4,  5,  6,  7,  8],
         [ 6,  7,  9, 10, 11]]])

In [16]:
import torch.nn as nn

In [17]:
rnn = nn.LSTM(10, 20, 2)
inp = torch.randn(5, 3, 10)
h0 = torch.randn(2, 3, 20)
c0 = torch.randn(2, 3, 20)
output, (hn, cn) = rnn(inp, (h0, c0))

In [18]:
output

tensor([[[ 1.5345e-01, -1.1607e-01,  3.0561e-02, -2.7565e-02, -1.1295e-01,
          -9.2120e-03,  3.6687e-01, -4.1609e-01,  1.6330e-01, -1.6371e-01,
           6.9888e-02,  5.5814e-01,  2.5615e-01, -1.0130e-01, -2.6010e-01,
           5.9335e-02, -1.7100e-01,  1.4186e-01,  7.5899e-02,  3.6941e-01],
         [-6.8451e-01,  2.6773e-01,  4.5162e-02, -1.7592e-01,  1.7980e-01,
          -7.0528e-02, -2.6328e-01,  5.4576e-02,  1.4892e-01, -1.1442e-02,
           2.9762e-01,  5.3621e-01, -2.9981e-01,  6.5323e-02, -3.2995e-01,
          -1.0770e-01, -1.6817e-01, -2.3955e-01, -3.0727e-02,  9.8401e-02],
         [-3.6695e-02, -1.2609e-01, -2.2673e-01, -1.0010e-01,  2.5725e-01,
           7.9664e-02, -3.1451e-01,  2.1308e-01,  1.1622e-01, -3.7149e-03,
          -3.2888e-01,  2.7705e-01, -2.8013e-01,  9.8036e-02,  3.3037e-02,
           7.0665e-03, -1.6415e-01,  5.8175e-01,  1.8648e-02,  2.4090e-02]],

        [[ 1.1239e-01,  2.1398e-02, -5.3075e-02,  5.9770e-02, -1.4246e-01,
          -1.0603e-0

In [19]:
rnn

LSTM(10, 20, num_layers=2)

In [21]:
import torch
import torch.nn as nn
inp = torch.tensor([1.0, 2.0, 3, 4, 5])

outplace_dropout = nn.Dropout(p=0.4)
print(inp)

tensor([1., 2., 3., 4., 5.])


In [22]:
output = outplace_dropout(inp)
print(output)

tensor([1.6667, 3.3333, 5.0000, 6.6667, 8.3333])


In [23]:
print(inp)

tensor([1., 2., 3., 4., 5.])


In [24]:
inplace_droput = nn.Dropout(p=0.4, inplace=True)
inplace_droput(inp)
print(inp) # Notice that the input is changed now

tensor([1.6667, 0.0000, 5.0000, 6.6667, 8.3333])


In [31]:
a = [1,2,4,6]
b = [6,9,0,3]
for _ in a:
    print(a, end=' ')
    

[1, 2, 4, 6] [1, 2, 4, 6] [1, 2, 4, 6] [1, 2, 4, 6] 

In [32]:
rnn = nn.LSTM(10, 20, 2)
inp = torch.randn(5, 3, 10)
h0 = torch.randn(2, 3, 20)
c0 = torch.randn(2, 3, 20)
output, (hn, cn) = rnn(inp, (h0, c0))

In [33]:
rnn

LSTM(10, 20, num_layers=2)